### ISSUE TITLE
Make functional version of this loop

### ISSUE THREAD

**Issue by trystant** [codyirving/TimeLapse#2]
https://github.com/codyirving/TimeLapse/blob/ef40f48316da767a6dd94aec1577cd2ae4887dd5/index.js#L12-L18

There is a way to make a functional version of this loop.

**Comment by trystant** [comment]
the route to this is through the `_.map` function.

**Comment by trystant** [comment]
@codyirving Hi there. I just wanted to give you a friendly reminder.

**Comment by codyirving** [comment]
Whole block was unnecessary.  Fixed, Thanks!
